// Chapter-wise syllabus for SSC (Maharashtra Board) and CBSE — Std X.
// STEM subjects (Maths, Science) are standard, stable textbook chapter lists.
// History & Political Science and Geography & Economics (SSC) were corrected
// against current Balbharati textbook indexes (verified Oct 2026 — see chat).
// Language-subject lists (Marathi/Hindi/English literature) are kept
// high-level since exact lesson titles vary by edition/medium.
// Always verify against the current official syllabus PDF (mahahsscboard.in /
// cbseacademic.nic.in) before publishing to students, as boards revise yearly.

export const sscChapters: Record<string, string[]> = {
  "maths-1": [
    "Linear Equations in Two Variables",
    "Quadratic Equations",
    "Arithmetic Progression",
    "Financial Planning",
    "Probability",
    "Statistics",
  ],
  "maths-2": [
    "Similarity",
    "Pythagoras Theorem",
    "Circle",
    "Geometric Constructions",
    "Co-ordinate Geometry",
    "Trigonometry",
    "Mensuration",
  ],
  "science-1": [
    "Gravitation",
    "Periodic Classification of Elements",
    "Chemical Reactions and Equations",
    "Effects of Electric Current",
    "Heat",
    "Refraction of Light",
    "Lenses",
    "Metallurgy",
    "Carbon Compounds",
    "Space Missions",
  ],
  "science-2": [
    "Heredity and Evolution",
    "Life Processes in Living Organisms — Part 1",
    "Life Processes in Living Organisms — Part 2",
    "Environmental Management",
    "Towards Green Energy",
    "Animal Classification",
    "Introduction to Microbiology",
    "Cell Biology and Biotechnology",
    "Social Health",
  ],
  // CORRECTED — verified against Balbharati textbook index (shaalaa.com,
  // omtexclasses.com, supertutor.in — all consistent, Oct 2026). The
  // previous list (1857 Revolt, Freedom Struggle, UN, etc.) was from an
  // older/different curriculum and did not match the current textbook.
  "history-polity": [
    "Historiography: Development in the West",
    "Historiography: Indian Tradition",
    "Applied History",
    "History of Indian Arts",
    "Mass Media and History",
    "Entertainment and History",
    "Sports and History",
    "Tourism and History",
    "Heritage Management",
    "Working of the Constitution",
    "The Electoral Process",
    "Political Parties",
    "Social and Political Movements",
    "Challenges Faced by Indian Democracy",
  ],
  // CORRECTED — verified against Balbharati "Geography and Economics"
  // (Social Sciences Part II) textbook index (studocu.com, shaalaa.com
  // Marathi edition — consistent). The previous list (National Income,
  // Globalisation, Foreign Trade, etc.) was fabricated, not sourced.
  "geography-economics": [
    "The Northern Mountain Region",
    "The Northern Plain Region — The Desert",
    "The Northern Plain Region — Punjab and Haryana Plains",
    "The Peninsular Plateau Region — Central Highlands",
    "The Peninsular Plateau Region — Deccan",
    "The Western Ghats and Coastal Plains",
    "Practical Geography",
    "Introduction to an Economy",
    "The Basic Problems of an Economy and Solutions",
    "Inflation",
    "The Public Distribution System and Consumer Protection",
  ],
  marathi: [
    "Prose & Poetry Unit 1 (per Kumarbharati textbook)",
    "Prose & Poetry Unit 2",
    "Prose & Poetry Unit 3",
    "Grammar (Vyakaran)",
    "Composition & Letter Writing",
  ],
  english: [
    "Prose & Poetry Unit 1 (per My English Coursebook)",
    "Prose & Poetry Unit 2",
    "Prose & Poetry Unit 3",
    "Grammar",
    "Writing Skills",
  ],
  hindi: [
    "Prose & Poetry Unit 1 (per Yuvakbharati/Lokbharati)",
    "Prose & Poetry Unit 2",
    "Grammar (Vyakaran)",
    "Composition & Letter Writing",
  ],
};

export const cbseChapters: Record<string, string[]> = {
  maths: [
    "Real Numbers",
    "Polynomials",
    "Pair of Linear Equations in Two Variables",
    "Quadratic Equations",
    "Arithmetic Progressions",
    "Triangles",
    "Coordinate Geometry",
    "Introduction to Trigonometry",
    "Some Applications of Trigonometry",
    "Circles",
    "Areas Related to Circles",
    "Surface Areas and Volumes",
    "Statistics",
    "Probability",
  ],
  // Note: "Constructions" was fully deleted from the CBSE 2025-26 syllabus —
  // confirmed via multiple exam-prep sources (Oct 2026) — correctly excluded here.
  science: [
    "Chemical Reactions and Equations",
    "Acids, Bases and Salts",
    "Metals and Non-metals",
    "Carbon and its Compounds",
    "Life Processes",
    "Control and Coordination",
    "Reproduction",
    "Heredity and Evolution",
    "Light — Reflection and Refraction",
    "The Human Eye and the Colourful World",
    "Electricity",
    "Magnetic Effects of Electric Current",
    "Our Environment",
  ],
  "social-science": [
    "The Rise of Nationalism in Europe",
    "Nationalism in India",
    "The Making of a Global World",
    "The Age of Industrialisation",
    "Print Culture and the Modern World",
    "Resources and Development",
    "Forest and Wildlife Resources",
    "Water Resources",
    "Agriculture",
    "Minerals and Energy Resources",
    "Manufacturing Industries",
    "Lifelines of National Economy",
    "Power Sharing",
    "Federalism",
    "Gender, Religion and Caste",
    "Political Parties",
    "Outcomes of Democracy",
    "Development",
    "Sectors of the Indian Economy",
    "Money and Credit",
    "Globalisation and the Indian Economy",
    "Consumer Rights",
  ],
  english: [
    "A Letter to God",
    "Nelson Mandela: Long Walk to Freedom",
    "Two Stories about Flying",
    "From the Diary of Anne Frank",
    "The Hundred Dresses I & II",
    "Glimpses of India",
    "Mijbil the Otter",
    "Madam Rides the Bus",
    "The Sermon at Benares",
    "The Proposal",
    "A Triumph of Surgery",
    "The Thief's Story",
    "The Midnight Visitor",
    "A Question of Trust",
    "Footprints without Feet",
    "The Making of a Scientist",
    "The Necklace",
    "Bholi",
    "The Book That Saved the Earth",
  ],
  hindi: [
    "Kshitij / Kritika Prose & Poetry Unit 1",
    "Kshitij / Kritika Prose & Poetry Unit 2",
    "Kshitij / Kritika Prose & Poetry Unit 3",
    "Grammar (Vyakaran)",
    "Writing Skills",
  ],
};
