// Chapter-wise syllabus for SSC (Maharashtra Board) and CBSE — Std X.
// STEM subjects (Maths, Science, Social Science) are standard, stable textbook
// chapter lists. Language-subject lists (Marathi/Hindi/English literature) are
// kept high-level since exact lesson titles vary by edition/medium.
// Verify against the current official syllabus PDF (mahahsscboard.in /
// cbseacademic.nic.in) before publishing to students, as boards revise yearly.

export const sscChapters: Record<string, string[]> = {
  "maths-1": [
    "Linear Equations in Two Variables",
    "Quadratic Equations",
    "Arithmetic Progression",
    "Financial Planning",
    "Probability",
    "Statistics",
  ],
  "maths-2": [
    "Similarity",
    "Pythagoras Theorem",
    "Circle",
    "Geometric Constructions",
    "Co-ordinate Geometry",
    "Trigonometry",
    "Mensuration",
  ],
  "science-1": [
    "Gravitation",
    "Periodic Classification of Elements",
    "Chemical Reactions and Equations",
    "Effects of Electric Current",
    "Heat",
    "Refraction of Light",
    "Lenses",
    "Metallurgy",
    "Carbon Compounds",
    "Space Missions",
  ],
  "science-2": [
    "Heredity and Evolution",
    "Life Processes in Living Organisms — Part 1",
    "Life Processes in Living Organisms — Part 2",
    "Environmental Management",
    "Towards Green Energy",
    "Animal Classification",
    "Introduction to Microbiology",
    "Cell Biology and Biotechnology",
    "Social Health",
  ],
  "history-polity": [
    "Historiography: Development in the West",
    "Historiography: Indian Tradition",
    "Applied History",
    "Sources of History",
    "India after the Fall of the Mughal Empire",
    "1857 - The Revolt and its Legacy",
    "The Freedom Struggle Part 1",
    "The Freedom Struggle Part 2",
    "India's Relations with Neighbouring Countries",
    "Non-Aligned Movement",
    "United Nations",
    "Social and Political Movements",
    "Science and Technology",
    "Journey towards Empowerment",
  ],
  "geography-economics": [
    "Location, Site and Situation",
    "Field Visit",
    "Latitude, Longitude and Time",
    "Physiography and Drainage",
    "Climate",
    "Natural Vegetation and Wildlife",
    "Population",
    "Human Settlements",
    "Economic Development",
    "National Income",
    "Money and Banking",
    "Globalisation",
    "Foreign Trade",
    "Tourism, Transport and Communication",
  ],
  marathi: [
    "Prose & Poetry Unit 1 (per Kumarbharati textbook)",
    "Prose & Poetry Unit 2",
    "Prose & Poetry Unit 3",
    "Grammar (Vyakaran)",
    "Composition & Letter Writing",
  ],
  english: [
    "Prose & Poetry Unit 1 (per My English Coursebook)",
    "Prose & Poetry Unit 2",
    "Prose & Poetry Unit 3",
    "Grammar",
    "Writing Skills",
  ],
  hindi: [
    "Prose & Poetry Unit 1 (per Yuvakbharati/Lokbharati)",
    "Prose & Poetry Unit 2",
    "Grammar (Vyakaran)",
    "Composition & Letter Writing",
  ],
};

export const cbseChapters: Record<string, string[]> = {
  maths: [
    "Real Numbers",
    "Polynomials",
    "Pair of Linear Equations in Two Variables",
    "Quadratic Equations",
    "Arithmetic Progressions",
    "Triangles",
    "Coordinate Geometry",
    "Introduction to Trigonometry",
    "Some Applications of Trigonometry",
    "Circles",
    "Areas Related to Circles",
    "Surface Areas and Volumes",
    "Statistics",
    "Probability",
  ],
  science: [
    "Chemical Reactions and Equations",
    "Acids, Bases and Salts",
    "Metals and Non-metals",
    "Carbon and its Compounds",
    "Life Processes",
    "Control and Coordination",
    "How do Organisms Reproduce?",
    "Heredity and Evolution",
    "Light — Reflection and Refraction",
    "The Human Eye and the Colourful World",
    "Electricity",
    "Magnetic Effects of Electric Current",
    "Our Environment",
  ],
  "social-science": [
    // History
    "The Rise of Nationalism in Europe",
    "Nationalism in India",
    "The Making of a Global World",
    "The Age of Industrialisation",
    "Print Culture and the Modern World",
    // Geography
    "Resources and Development",
    "Forest and Wildlife Resources",
    "Water Resources",
    "Agriculture",
    "Minerals and Energy Resources",
    "Manufacturing Industries",
    "Lifelines of National Economy",
    // Political Science (Civics)
    "Power Sharing",
    "Federalism",
    "Gender, Religion and Caste",
    "Political Parties",
    "Outcomes of Democracy",
    // Economics
    "Development",
    "Sectors of the Indian Economy",
    "Money and Credit",
    "Globalisation and the Indian Economy",
    "Consumer Rights",
  ],
  english: [
    // First Flight
    "A Letter to God",
    "Nelson Mandela: Long Walk to Freedom",
    "Two Stories about Flying",
    "From the Diary of Anne Frank",
    "The Hundred Dresses I & II",
    "Glimpses of India",
    "Mijbil the Otter",
    "Madam Rides the Bus",
    "The Sermon at Benares",
    "The Proposal",
    // Footprints without Feet
    "A Triumph of Surgery",
    "The Thief's Story",
    "The Midnight Visitor",
    "A Question of Trust",
    "Footprints without Feet",
    "The Making of a Scientist",
    "The Necklace",
    "Bholi",
    "The Book That Saved the Earth",
  ],
  hindi: [
    "Kshitij / Kritika Prose & Poetry Unit 1",
    "Kshitij / Kritika Prose & Poetry Unit 2",
    "Kshitij / Kritika Prose & Poetry Unit 3",
    "Grammar (Vyakaran)",
    "Writing Skills",
  ],
};
